"""ATT&CK coverage documentation generator.

Reads the attack.* tags of every rule and produces:

* docs/coverage.md: a table of tactic / technique / covering rules, plus
  an honest gap section listing every tactic with zero coverage.
* docs/navigator_layer.json: an ATT&CK Navigator layer scoring each
  covered technique by rule count, for visualization on the real matrix.

Output is deterministic (sorted, no timestamps) so regenerating without
rule changes produces no diff, which is what the CI freshness check
relies on.

CLI: python -m sigmaforge.coverage [--check]
     --check exits 1 if the files on disk are stale instead of writing.
"""

from __future__ import annotations

import json
import re
import sys
from collections import defaultdict
from pathlib import Path

import yaml
from sigma.data.mitre_attack import (
    mitre_attack_tactics,
    mitre_attack_techniques,
    mitre_attack_version,
)

from sigmaforge.loader import REPO_ROOT, discover_rule_paths

DOCS_DIR = REPO_ROOT / "docs"
COVERAGE_MD = DOCS_DIR / "coverage.md"
NAVIGATOR_JSON = DOCS_DIR / "navigator_layer.json"

TECHNIQUE_TAG_RE = re.compile(r"^attack\.(t\d{4}(?:\.\d{3})?)$")
NON_TACTIC_TAG_RE = re.compile(r"^attack\.[tgsm]\d{4}(\.\d{3})?$")


def collect_coverage() -> tuple[dict[str, dict[str, set[str]]], dict[str, set[str]]]:
    """Return (tactic -> technique_id -> rule names, technique_id -> rule names)."""
    by_tactic: dict[str, dict[str, set[str]]] = defaultdict(lambda: defaultdict(set))
    by_technique: dict[str, set[str]] = defaultdict(set)
    for rule_path in discover_rule_paths():
        raw = yaml.safe_load(rule_path.read_text(encoding="utf-8"))
        tags = [str(t) for t in raw.get("tags") or []]
        techniques = [
            m.group(1).upper() for t in tags if (m := TECHNIQUE_TAG_RE.match(t))
        ]
        tactics = [
            t.removeprefix("attack.")
            for t in tags
            if t.startswith("attack.") and not NON_TACTIC_TAG_RE.match(t)
        ]
        for technique in techniques:
            by_technique[technique].add(rule_path.stem)
            for tactic in tactics:
                by_tactic[tactic][technique].add(rule_path.stem)
    return by_tactic, by_technique


def technique_name(technique_id: str) -> str:
    return mitre_attack_techniques.get(technique_id, "(unknown technique)")


def render_coverage_md() -> str:
    by_tactic, by_technique = collect_coverage()
    all_tactics = sorted(set(mitre_attack_tactics.values()))
    covered_tactics = sorted(by_tactic)
    uncovered = [t for t in all_tactics if t not in by_tactic]

    lines = [
        "# ATT&CK Coverage",
        "",
        "Generated by `make coverage` from the tags of every rule under `rules/`.",
        "Do not edit by hand. CI fails if this file is out of date.",
        "",
        f"MITRE ATT&CK version: {mitre_attack_version}",
        "",
        f"Rules: {len(discover_rule_paths())}. "
        f"Techniques covered: {len(by_technique)}. "
        f"Tactics covered: {len(covered_tactics)} of {len(all_tactics)}.",
        "",
        "## Coverage by tactic",
        "",
        "| Tactic | Technique | Name | Rules |",
        "| --- | --- | --- | --- |",
    ]
    for tactic in covered_tactics:
        for technique in sorted(by_tactic[tactic]):
            rules = ", ".join(
                f"[{name}](../rules/windows/{name}.yml)"
                for name in sorted(by_tactic[tactic][technique])
            )
            lines.append(
                f"| {tactic} | {technique} | {technique_name(technique)} | {rules} |"
            )
    lines += [
        "",
        "## Tactics with zero coverage",
        "",
    ]
    if uncovered:
        lines += [f"- {tactic}" for tactic in uncovered]
    else:
        lines.append("None. Every tactic has at least one rule.")
    lines += [
        "",
        "Zero-coverage tactics are honest gaps, not oversights in this doc. "
        "If a tactic matters for your environment and is listed above, that "
        "is where the next rule should go.",
        "",
    ]
    return "\n".join(lines)


def render_navigator_layer() -> str:
    _, by_technique = collect_coverage()
    max_rules = max((len(r) for r in by_technique.values()), default=1)
    layer = {
        "name": "SigmaForge coverage",
        "description": "Rule coverage generated by sigmaforge.coverage",
        "domain": "enterprise-attack",
        "versions": {
            "attack": str(mitre_attack_version).split(".")[0],
            "navigator": "5.1.0",
            "layer": "4.5",
        },
        "sorting": 0,
        "layout": {"layout": "side", "showID": True, "showName": True},
        "hideDisabled": False,
        "techniques": [
            {
                "techniqueID": technique,
                "score": len(rules),
                "comment": "Rules: " + ", ".join(sorted(rules)),
            }
            for technique, rules in sorted(by_technique.items())
        ],
        "gradient": {
            "colors": ["#ffe766", "#8ec843"],
            "minValue": 0,
            "maxValue": max_rules,
        },
        "legendItems": [],
        "showTacticRowBackground": False,
        "selectTechniquesAcrossTactics": True,
    }
    return json.dumps(layer, indent=2) + "\n"


def generate() -> dict[Path, str]:
    return {
        COVERAGE_MD: render_coverage_md(),
        NAVIGATOR_JSON: render_navigator_layer(),
    }


def main(argv: list[str] | None = None) -> int:
    args = sys.argv[1:] if argv is None else argv
    check = "--check" in args
    stale = []
    for path, content in generate().items():
        current = path.read_text(encoding="utf-8") if path.is_file() else None
        if current != content:
            stale.append(path)
        if not check:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content, encoding="utf-8", newline="\n")
    if check and stale:
        names = ", ".join(str(p.relative_to(REPO_ROOT)) for p in stale)
        print(
            f"Coverage docs out of date: {names}. Run 'make coverage' and commit.",
            file=sys.stderr,
        )
        return 1
    if not check:
        for path in generate():
            print(f"wrote {path.relative_to(REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
